core/urls.py
from django.urls import path
from .views import (
HomeView,
ExamView,
CourseView,
CourseCreateView,
course_single,
AssignmentCreateView,
AssignmentView,
AssignmentDeleteView,
ExamCreateView,
ExamListView,
AssignmentSubmissionView,
ExamDeleteView,
ExamSubmissionView,
ExamSubmissionListView,
AssignmentSubmissionListView,
AssignmentSubmissionDelete,
ExamSubmissionDelete

)
from django.conf import settings
from django.conf.urls.static import static

app_name = "core"

urlpatterns = [
                  path('', HomeView.as_view(), name='home'),
                  path('exam/', ExamView.as_view(), name='exam'),
                  path('course/', CourseView.as_view(), name='course'),
                  path('course-create/', CourseCreateView.as_view(), name='course-create'),
                  path('assignment-create/', AssignmentCreateView.as_view(), name='assignment-create'),
                  path('assignment/', AssignmentView.as_view(), name='assignment-list'),
                  path('<pk>/delete/', AssignmentDeleteView.as_view(), name='delete-assignment'),
                  path('<int:id>/course-view/', course_single, name='course-view'),
                  path('exam-create/', ExamCreateView.as_view(), name='exam-create'),
                  path('exam-list/', ExamListView.as_view(), name='exam-list'),
                  path('<pk>/delete/', ExamDeleteView.as_view(), name='delete-exam'),
                  path('assignment-submission/', AssignmentSubmissionView.as_view(), name='assignment-submission'),
                  path('exam-submission/', ExamSubmissionView.as_view(), name='exam-submission'),
                  path('exam-submission-list/', ExamSubmissionListView.as_view(), name='exam-submission-list'),
                  path('assignment-submission-list/', AssignmentSubmissionListView.as_view(), name='assignment-submission-list'),
                  path('<pk>/delete/', AssignmentSubmissionDelete.as_view(), name='assignment-submission-delete'),
                  path('<pk>/delete/', ExamSubmissionDelete.as_view(), name='exam-submission-delete'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab_exam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('', include('core.urls', namespace='core')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from authentication.models import User
from django.utils import timezone


class Course(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course_name = models.CharField(max_length=100)
    course_image = models.ImageField(upload_to='media')
    teacher_name = models.CharField(max_length=50)
    teacher_details = models.TextField()
    course_description = models.TextField()
    created_at = models.DateField(default=timezone.now)
    end_date = models.CharField(max_length=20)

    def __str__(self):
        return self.course_name


class Assignment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    marks = models.CharField(max_length=20)
    duration = models.CharField(max_length=100)
    created_at = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.title


class Exam(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    marks = models.CharField(max_length=20)
    duration = models.CharField(max_length=100)
    created_at = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.title


class AssignmentSubmission(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    university_id = models.CharField(max_length=100)
    content = models.TextField(null=True, blank=True)
    file = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.university_id


class ExamSubmission(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    university_id = models.CharField(max_length=100)
    content = models.TextField(null=True, blank=True)
    file = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.university_id

core/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, CreateView, ListView, DeleteView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from authentication.decorators import user_is_instructor, user_is_student

from .forms import CourseCreateForm, AssignmentCreateForm, ExamCreateForm, AssignmentSubmissionForm, ExamSubmissionForm
from .models import Course, Assignment, Exam, ExamSubmission, AssignmentSubmission


class HomeView(ListView):
    paginate_by = 6
    template_name = 'home.html'
    model = Course
    context_object_name = 'course'

    def get_queryset(self):
        return self.model.objects.all()


class ExamView(TemplateView):
    template_name = 'core/exams.html'


# COURSE CREATE VIEW
class CourseCreateView(CreateView):
    template_name = 'core/instructor/course_create.html'
    form_class = CourseCreateForm
    extra_context = {
        'title': 'New Course'
    }
    success_url = reverse_lazy('core:course')

    @method_decorator(login_required(login_url=reverse_lazy('authentication:login')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('authentication:login')
        if self.request.user.is_authenticated and self.request.user.role != 'instructor':
            return reverse_lazy('authentication:login')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CourseCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


# VIEW FOR COURSE LIST
class CourseView(ListView):
    model = Course
    template_name = 'core/instructor/courses.html'
    context_object_name = 'course'

    @method_decorator(login_required(login_url=reverse_lazy('authentication:login')))
    # @method_decorator(user_is_instructor, user_is_student)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.all().order_by('-id')  # filter(user_id=self.request.user.id).order_by('-id')


def course_single(request, id):
    course = get_object_or_404(Course, id=id)
    return render(request, "core/instructor/view_course.html", {'course': course})


# ASSIGNMENT CREATE VIEW
class AssignmentCreateView(CreateView):
    template_name = 'core/instructor/assignment_create.html'
    form_class = AssignmentCreateForm
    extra_context = {
        'title': 'New Course'
    }
    success_url = reverse_lazy('core:assignment-list')

    @method_decorator(login_required(login_url=reverse_lazy('authentication:login')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('authentication:login')
        if self.request.user.is_authenticated and self.request.user.role != 'instructor':
            return reverse_lazy('authentication:login')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(AssignmentCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


# VIEW FOR ASSIGNMENT LIST
class AssignmentView(ListView):
    model = Assignment
    template_name = 'core/instructor/assignments.html'
    context_object_name = 'assignment'

    @method_decorator(login_required(login_url=reverse_lazy('authentication:login')))
    # @method_decorator(user_is_student, user_is_instructor)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.all()  # filter(user_id=self.request.user.id).order_by('-id')


# DELETE ASSIGNMENT VIEW
class AssignmentDeleteView(DeleteView):
    model = Assignment
    success_url = reverse_lazy('core:assignment-list')


# ASSIGNMENT SUBMISSION VIEW
class AssignmentSubmissionView(CreateView):
    template_name = 'core/instructor/assignment_submission.html'
    form_class = AssignmentSubmissionForm
    extra_context = {
        'title': 'New Exam'
    }
    success_url = reverse_lazy('core:home')

    @method_decorator(login_required(login_url=reverse_lazy('authentication:login')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('authentication:login')
        if self.request.user.is_authenticated and self.request.user.role != 'student':
            return reverse_lazy('authentication:login')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(AssignmentSubmissionView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


# EXAM CREATE VIEW
class ExamCreateView(CreateView):
    template_name = 'core/instructor/exam_create.html'
    form_class = ExamCreateForm
    extra_context = {
        'title': 'New Exam'
    }
    success_url = reverse_lazy('core:exam-list')

    @method_decorator(login_required(login_url=reverse_lazy('authentication:login')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('authentication:login')
        if self.request.user.is_authenticated and self.request.user.role != 'instructor':
            return reverse_lazy('authentication:login')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ExamCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


# EXAM LIST VIEW
class ExamListView(ListView):
    model = Exam
    template_name = 'core/instructor/exam_list.html'
    context_object_name = 'exam'

    @method_decorator(login_required(login_url=reverse_lazy('authentication:login')))
    # @method_decorator(user_is_instructor)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.all().order_by('-id')  # filter(user_id=self.request.user.id).order_by('-id')


# EXAM DELETE VIEW
class ExamDeleteView(DeleteView):
    model = Exam
    success_url = reverse_lazy('core:exam-list')


# EXAM SUBMISSION VIEW
class ExamSubmissionView(CreateView):
    template_name = 'core/instructor/exam_submission.html'
    form_class = ExamSubmissionForm
    extra_context = {
        'title': 'New Exam'
    }
    success_url = reverse_lazy('core:home')

    @method_decorator(login_required(login_url=reverse_lazy('authentication:login')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('authentication:login')
        if self.request.user.is_authenticated and self.request.user.role != 'student':
            return reverse_lazy('authentication:login')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ExamSubmissionView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


# VIEW FOR Assignment Submission List
class AssignmentSubmissionListView(ListView):
    model = AssignmentSubmission
    template_name = 'core/instructor/assignment_submission_list.html'
    context_object_name = 'assignment_submission'

    @method_decorator(login_required(login_url=reverse_lazy('authentication:login')))
    # @method_decorator(user_is_instructor, user_is_student)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.all().order_by('-id')  # filter(user_id=self.request.user.id).order_by('-id')


# EXAM DELETE VIEW
class AssignmentSubmissionDelete(DeleteView):
    model = AssignmentSubmission
    success_url = reverse_lazy('core:assignment-submission-list')


# VIEW FOR Assignment Submission List
class ExamSubmissionListView(ListView):
    model = ExamSubmission
    template_name = 'core/instructor/exam_submission_list.html'
    context_object_name = 'exam_submission'

    @method_decorator(login_required(login_url=reverse_lazy('authentication:login')))
    # @method_decorator(user_is_instructor, user_is_student)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.all().order_by('-id')  # filter(user_id=self.request.user.id).order_by('-id')


class ExamSubmissionDelete(DeleteView):
    model = ExamSubmission
    success_url = reverse_lazy('core:exam-submission-list')

templates/core/instructor/assignment_create.html
 {% extends 'base.html' %}

{% load bootstrap %}

{% block title %} Assignment Create {% endblock %}

{% block content %}

    <section class="dentist-area section-padding-40-0">
<div class="container">

<div class="row justify-content-center">

                <div class="col-lg-5 mb-5 mb-lg-0">
                    <center> <h3> Create Assignment </h3></center>
                          <br/>
                    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}

                        {{ form|bootstrap }}

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Create" class="btn btn-primary btn-md text-white">
                            </div>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

templates/core/instructor/assignment_submission.html
 {% extends 'base.html' %}

{% load bootstrap %}

{% block title %} Assignment Submission {% endblock %}

{% block content %}

    <section class="dentist-area section-padding-40-0">
<div class="container">

<div class="row justify-content-center">

                <div class="col-lg-5 mb-5 mb-lg-0">
                    <center> <h3> Submit Assignment </h3></center>
                          <br/>
                    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}

                        {{ form|bootstrap }}

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Submit" class="btn btn-primary btn-md text-white">
                            </div>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

templates/core/instructor/assignment_submission_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Assignments{% endblock %}


{% block content %}

    <div class="container">

        <div class="col-12 col-sm-6 col-md-10">
                    <strong><h3>Assignments</h3></strong>
        <hr/>
            {% for foo in assignment_submission %}


                <p> <h4>Name</h4> {{ foo.name }} </p>

                <p> <h4>Id</h4> {{ foo.university_id }} </p>
                <hr/>
                <p> <h4>Answer</h4> {{ foo.content }}  </p>

                <br/>
                <a href="{% url 'core:assignment-submission-delete' foo.id %}">Delete Assignment</a>
                  <hr/>
            {% endfor %}




            <br/>


            <br/>


        </div>

    </div>

{% endblock %}

templates/core/instructor/assignments.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Assignments{% endblock %}


{% block content %}

    <div class="container">

        <div class="col-12 col-sm-6 col-md-10">
            {% if request.user.is_authenticated and request.user.role == 'instructor' %}
                {% for foo in assignment %}
                    <h3><strong> {{ foo.title }}  </strong></h3>
                    <hr/>
                    <p> <h4>Content</h4> {{ foo.content }} </p>
                    <br/>
                    <p> <h4>Marks</h4> {{ foo.marks }} </p>

                    <p> <h4>Time</h4> {{ foo.duration }} hours </p>

                    <a href="{% url 'core:delete-assignment' foo.id %}">Delete Assignment</a>

                {% endfor %}
                <hr/>


                <h4><a href="{% url 'core:assignment-create' %}">Create a Assignment</a></h4>


            {% else %}


                {% for foo in assignment %}
                    <h3><strong> {{ foo.title }}  </strong></h3>
                    <hr/>
                    <p> <h4>Content</h4> {{ foo.content }} </p>
                    <br/>
                    <p> <h4>Marks</h4> {{ foo.marks }} </p>

                    <p> <h4>Time</h4> {{ foo.duration }} hours </p>
                          <br/>
                      <h4><a href="{% url 'core:assignment-submission' %}">Submit Assignment</a></h4>
                  <hr/>
                {% endfor %}
                <hr/>


            {% endif %}
            <br/>
        </div>

    </div>

{% endblock %}

templates/core/instructor/course_create.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block title %} Course Create {% endblock %}

{% block content %}

    <section class="dentist-area section-padding-40-0">
<div class="container">

<div class="row justify-content-center">

                <div class="col-lg-5 mb-5 mb-lg-0">
                    <center> <h3>Create Course</h3></center>

                    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}

                        {{ form|bootstrap }}

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Create" class="btn btn-primary btn-md text-white">
                            </div>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

templates/core/instructor/courses.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Courses{% endblock %}


{% block content %}

    <div class="container">


      <div class="row">

        <!-- Section Heading -->
        <div class="col-12">
          <div class="section-heading text-center">


            <h3>{{ request.user.first_name }}'s Course/s</h3>
            <div class="line"></div>
          </div>
        </div>
      </div>

      <div class="row">
          {% for course in course %}
        <!-- Single Dentist Area -->
        <div class="col-12 col-sm-6 col-md-4">

          <div class="single-dentist-area mb-100">
            <img  style="height: 300px; width: 500px " src="{{ course.course_image.url }}" alt="">
            <!-- Dentist Content -->
            <div class="dentist-content">
              <!-- Social Info -->
              <div class="dentist-social-info">

              </div>
              <!-- Dentist Info -->
              <div class="dentist-info bg-gradient-overlay">
                  <h5>{{ course.course_name }} |  <a href="{% url 'core:course-view' course.id %}"> <small>VIEW COURSE</small></a> </h5>
                <p>{{ course.teacher_name }} </p>


              </div>
            </div>
          </div>
        </div>
      {% endfor %}

      </div>
    </div>

{% endblock %}

templates/core/instructor/exam_create.html
 {% extends 'base.html' %}

{% load bootstrap %}

{% block title %} Exam Create {% endblock %}

{% block content %}

    <section class="dentist-area section-padding-40-0">
<div class="container">

<div class="row justify-content-center">

                <div class="col-lg-5 mb-5 mb-lg-0">
                    <center> <h3> Create Exam </h3></center>
                          <br/>
                    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}

                        {{ form|bootstrap }}

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Create" class="btn btn-primary btn-md text-white">
                            </div>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

templates/core/instructor/exam_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Exams{% endblock %}


{% block content %}

    <div class="container">

        <div class="col-12 col-sm-6 col-md-10">
            {% if request.user.is_authenticated and request.user.role == 'instructor' %}
                {% for foo in exam %}
                    <h3><strong> {{ foo.title }}  </strong></h3>
                    <hr/>
                    <p> <h4>Content</h4> {{ foo.content }} </p>
                    <br/>
                    <p> <h4>Marks</h4> {{ foo.marks }} </p>

                    <p> <h4>Time</h4> {{ foo.duration }} hours </p>
                    <a href="{% url 'core:delete-exam' foo.id %}">Delete Exam</a>
                {% endfor %}
                <hr/>
                <h4><a href="{% url 'core:exam-create' %}">Create a Exam</a></h4>

                <br/>
            {% else %}


                {% for foo in exam %}
                    <h3><strong> {{ foo.title }}  </strong></h3>
                    <hr/>
                    <p> <h4>Content</h4> {{ foo.content }} </p>
                    <br/>
                    <p> <h4>Marks</h4> {{ foo.marks }} </p>

                    <p> <h4>Time</h4> {{ foo.duration }} hours </p>
                     <br/>
                   <h4><a href="{% url 'core:exam-submission' %}">Submit Exam Paper</a></h4>
                       <hr/>
                {% endfor %}



                <br/>

            {% endif %}
        </div>

    </div>

{% endblock %}

templates/core/instructor/exam_submission.html
 {% extends 'base.html' %}

{% load bootstrap %}

{% block title %} Exam Paper Submission {% endblock %}

{% block content %}

    <section class="dentist-area section-padding-40-0">
<div class="container">

<div class="row justify-content-center">

                <div class="col-lg-5 mb-5 mb-lg-0">
                    <center> <h3> Submit Exam Paper </h3></center>
                          <br/>
                    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}

                        {{ form|bootstrap }}

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Submit" class="btn btn-primary btn-md text-white">
                            </div>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

templates/core/instructor/exam_submission_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Exam Submissions{% endblock %}


{% block content %}

    <div class="container">

        <div class="col-12 col-sm-6 col-md-10">
                    <strong><h3>Exam Submissions</h3></strong>
        <hr/>
            {% for foo in exam_submission %}


                <p> <h4>Name</h4> {{ foo.name }} </p>

                <p> <h4>Id</h4> {{ foo.university_id }} </p>
                <hr/>
                <p> <h4>Answer</h4> {{ foo.content }}  </p>

                <br/>
                <a href="{% url 'core:exam-submission-delete' foo.id %}">Delete </a>
                  <hr/>
            {% endfor %}




            <br/>


            <br/>


        </div>

    </div>

{% endblock %}

templates/core/instructor/view_course.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Courses{% endblock %}


{% block content %}

    <div class="container">

    <div class="col-12 col-sm-6 col-md-10">


             <h3><strong>{{ course.course_name }}  </strong></h3>
              <br/>
            <img  style=" height: 300px; width: 900px  " src="{{ course.course_image.url }}" alt="">


                         <hr/>
                  <h4> <strong>Instructor :</strong> {{ course.teacher_name }} </h4>
                           <br/>
                  <p> <h4>About Instructor </h4>{{ course.teacher_details }} </p>
                          <br/>
                  <p> <h4>About Course </h4>{{ course.course_description }} </p>

                          <br/>
                  <h4><a href="{% url 'core:assignment-list' %}">Assignments </a></h4>
                           <br/>
                  <h4><a href="{% url 'core:exam-list' %}">Exams </a> </h4>
                           <br/>
                  <p>  <h4>Course Duration </h4>{{ course.created_at }} - {{ course.end_date }} </p>




         </div>

    </div>

{% endblock %}